%YAML:1.0
---
image_width: 640
image_height: 576
camera_name: camera_depth_optical_frame
camera_matrix: !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [ 5.0508520507812500e+02, 0., 3.3796063232421875e+02, 0.,
       5.0502670288085938e+02, 3.3832763671875000e+02, 0., 0., 1. ]
distortion_model: plumb_bob
distortion_coefficients: !!opencv-matrix
   rows: 1
   cols: 8
   dt: d
   data: [ 1.8535823822021484e+01, 8.5785322189331055e+00,
       9.7466145234648138e-05, 3.0213110221666284e-05,
       2.7301293611526489e-01, 1.8849531173706055e+01,
       1.4825737953186035e+01, 1.8621672391891479e+00 ]
rectification_matrix: !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [ 1., 0., 0., 0., 1., 0., 0., 0., 1. ]
projection_matrix: !!opencv-matrix
   rows: 3
   cols: 4
   dt: d
   data: [ 5.0508520507812500e+02, 0., 3.3796063232421875e+02, 0., 0.,
       5.0502670288085938e+02, 3.3832763671875000e+02, 0., 0., 0., 1.,
       0. ]
