session_created_at: '2025-11-11T11:25:17.150'
frames:
  T_tool0_color:
    parent: ur20_tool0
    child: femto_color_optical_calib
    xyz:
    - -0.03107523
    - 0.15939788
    - -0.03590129
    rpy:
    - 1.5841068999999994
    - 0.008359600000000002
    - -3.1385739
    quat_xyzw:
    - -0.004010177799601098
    - 0.7117856250445744
    - 0.7023827127831601
    - 0.001915003208574325
  T_tool0_ir:
    parent: ur20_tool0
    child: femto_ir_optical_calib
    xyz:
    - 0.0004368
    - 0.16222267
    - -0.03703682
    rpy:
    - 1.4800043000000003
    - 0.0037693999999999987
    - -3.1355591
    quat_xyzw:
    - -0.0034259560194477047
    - 0.6742810347295718
    - 0.7384662709048851
    - -0.000956956218276448
